use std::collections::HashMap;
use std::path::PathBuf;

use sha2::{Digest, Sha256};

use loom_core::build::context::BuildContext;
use loom_core::error::LoomError;
use loom_core::plugin::backend::Diagnostic;
use loom_core::plugin::generator::{GeneratorPlugin, GeneratorResult};

/// Generator plugin for Vivado IP instantiation.
///
/// Generates Tcl scripts to create and customize Vivado IP cores via their VLNV
/// (vendor:library:name:version) identifier.
pub struct VivadoIpGenerator;

impl GeneratorPlugin for VivadoIpGenerator {
    fn plugin_name(&self) -> &str {
        "vivado_ip"
    }

    fn check_environment(&self) -> Result<Vec<Diagnostic>, LoomError> {
        match std::process::Command::new("vivado")
            .arg("-version")
            .output()
        {
            Ok(output) if output.status.success() => Ok(vec![]),
            _ => Ok(vec![Diagnostic {
                severity: loom_core::plugin::backend::DiagnosticSeverity::Error,
                message: "Vivado not found on PATH. Install Vivado and source settings64.sh, \
                     or set XILINX_VIVADO environment variable."
                    .to_string(),
                source_path: None,
                line: None,
            }]),
        }
    }

    fn validate_config(&self, config: &toml::Value) -> Result<Vec<Diagnostic>, LoomError> {
        let mut diagnostics = Vec::new();

        let vlnv = config.get("vlnv").and_then(|v| v.as_str());
        if vlnv.is_none() {
            diagnostics.push(Diagnostic {
                severity: loom_core::plugin::backend::DiagnosticSeverity::Error,
                message:
                    "vivado_ip generator requires 'vlnv' field (e.g. 'xilinx.com:ip:clk_wiz:6.0')"
                        .to_string(),
                source_path: None,
                line: None,
            });
            return Ok(diagnostics);
        }

        // Validate VLNV format: vendor:library:name or vendor:library:name:version
        let vlnv_str = vlnv.unwrap();
        let parts: Vec<&str> = vlnv_str.split(':').collect();
        if parts.len() < 3 || parts.len() > 4 {
            diagnostics.push(Diagnostic {
                severity: loom_core::plugin::backend::DiagnosticSeverity::Error,
                message: format!(
                    "Invalid VLNV format '{}'. Expected 'vendor:library:name' or 'vendor:library:name:version'",
                    vlnv_str
                ),
                source_path: None,
                line: None,
            });
        }

        Ok(diagnostics)
    }

    fn compute_cache_key(
        &self,
        config: &toml::Value,
        input_hashes: &HashMap<String, String>,
    ) -> Result<String, LoomError> {
        let mut hasher = Sha256::new();
        hasher.update(b"vivado_ip\0");

        if let Some(vlnv) = config.get("vlnv").and_then(|v| v.as_str()) {
            hasher.update(vlnv.as_bytes());
        }
        hasher.update(b"\0");

        // Include properties in cache key
        if let Some(props) = config.get("properties").and_then(|v| v.as_table()) {
            let mut sorted: Vec<_> = props.iter().collect();
            sorted.sort_by_key(|(k, _)| k.as_str());
            for (k, v) in sorted {
                hasher.update(k.as_bytes());
                hasher.update(b"=");
                hasher.update(v.to_string().as_bytes());
                hasher.update(b"\0");
            }
        }

        // Include tool version from env if available
        if let Some(ver) = config.get("tool_version").and_then(|v| v.as_str()) {
            hasher.update(b"tool_version:");
            hasher.update(ver.as_bytes());
            hasher.update(b"\0");
        }

        // Include input hashes
        let mut sorted: Vec<_> = input_hashes.iter().collect();
        sorted.sort_by_key(|(k, _)| k.as_str());
        for (path, hash) in sorted {
            hasher.update(path.as_bytes());
            hasher.update(b":");
            hasher.update(hash.as_bytes());
            hasher.update(b"\0");
        }

        Ok(hex::encode(hasher.finalize()))
    }

    fn execute(
        &self,
        config: &toml::Value,
        _context: &BuildContext,
    ) -> Result<GeneratorResult, LoomError> {
        let vlnv = config.get("vlnv").and_then(|v| v.as_str()).ok_or_else(|| {
            LoomError::Internal("vivado_ip: 'vlnv' field is required".to_string())
        })?;

        let output_dir = config
            .get("output_dir")
            .and_then(|v| v.as_str())
            .ok_or_else(|| {
                LoomError::Internal("vivado_ip: 'output_dir' not provided in config".to_string())
            })?;

        // Extract the IP name from VLNV (third component)
        let ip_name = vlnv.split(':').nth(2).unwrap_or("ip_core");

        // Generate Tcl script
        let mut tcl = String::new();
        tcl.push_str("# Auto-generated by Loom vivado_ip generator\n");
        tcl.push_str(&format!(
            "create_ip -vlnv {} -module_name {} -dir {}\n",
            vlnv, ip_name, output_dir
        ));

        // Apply properties
        if let Some(props) = config.get("properties").and_then(|v| v.as_table()) {
            for (key, value) in props {
                let val_str = match value {
                    toml::Value::String(s) => s.clone(),
                    other => other.to_string(),
                };
                tcl.push_str(&format!(
                    "set_property -dict [list CONFIG.{} {{{}}}] [get_ips {}]\n",
                    key, val_str, ip_name
                ));
            }
        }

        // Support tcl_config escape hatch (§6.5 spec)
        if let Some(tcl_config) = config.get("tcl_config").and_then(|v| v.as_str()) {
            tcl.push_str(&format!("source {}\n", tcl_config));
        }

        tcl.push_str(&format!("generate_target all [get_ips {}]\n", ip_name));

        // Write Tcl script
        let tcl_path = PathBuf::from(output_dir).join(format!("{}_gen.tcl", ip_name));
        std::fs::create_dir_all(output_dir).map_err(|e| LoomError::Io {
            path: PathBuf::from(output_dir),
            source: e,
        })?;
        std::fs::write(&tcl_path, &tcl).map_err(|e| LoomError::Io {
            path: tcl_path.clone(),
            source: e,
        })?;

        // Try to execute Vivado, but gracefully handle missing tool
        let vivado_result = std::process::Command::new("vivado")
            .args(["-mode", "batch", "-source"])
            .arg(&tcl_path)
            .current_dir(output_dir)
            .output();

        match vivado_result {
            Ok(output) => {
                if !output.status.success() {
                    let stderr = String::from_utf8_lossy(&output.stderr);
                    return Err(LoomError::Internal(format!(
                        "Vivado IP generation failed: {}",
                        stderr.lines().next().unwrap_or("unknown error")
                    )));
                }

                // Collect produced files (XCI + output products)
                let mut produced = vec![tcl_path];
                let xci_path = PathBuf::from(output_dir).join(format!("{}.xci", ip_name));
                if xci_path.exists() {
                    produced.push(xci_path);
                }

                Ok(GeneratorResult {
                    success: true,
                    produced_files: produced,
                    log: String::from_utf8_lossy(&output.stdout)
                        .lines()
                        .map(String::from)
                        .collect(),
                })
            }
            Err(_) => {
                // Vivado not on PATH — return the Tcl script as the only output
                // so the build can still proceed (the script will be sourced later)
                Err(LoomError::ToolNotFound {
                    tool: "vivado".to_string(),
                    message: "Vivado not found on PATH. Install Vivado and source settings64.sh."
                        .to_string(),
                })
            }
        }
    }

    fn clean(&self, config: &toml::Value, _context: &BuildContext) -> Result<(), LoomError> {
        if let Some(output_dir) = config.get("output_dir").and_then(|v| v.as_str()) {
            let path = PathBuf::from(output_dir);
            if path.exists() {
                std::fs::remove_dir_all(&path).map_err(|e| LoomError::Io { path, source: e })?;
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_validate_missing_vlnv() {
        let gen = VivadoIpGenerator;
        let config: toml::Value = toml::from_str("key = \"value\"").unwrap();
        let diags = gen.validate_config(&config).unwrap();
        assert!(!diags.is_empty());
        assert!(diags[0].message.contains("vlnv"));
    }

    #[test]
    fn test_validate_valid_vlnv() {
        let gen = VivadoIpGenerator;
        let config: toml::Value = toml::from_str("vlnv = \"xilinx.com:ip:clk_wiz:6.0\"").unwrap();
        let diags = gen.validate_config(&config).unwrap();
        assert!(diags.is_empty());
    }

    #[test]
    fn test_validate_invalid_vlnv_format() {
        let gen = VivadoIpGenerator;
        let config: toml::Value = toml::from_str("vlnv = \"bad_format\"").unwrap();
        let diags = gen.validate_config(&config).unwrap();
        assert!(!diags.is_empty());
        assert!(diags[0].message.contains("Invalid VLNV"));
    }

    #[test]
    fn test_cache_key_deterministic() {
        let gen = VivadoIpGenerator;
        let config: toml::Value = toml::from_str("vlnv = \"xilinx.com:ip:clk_wiz:6.0\"").unwrap();
        let hashes = HashMap::new();
        let k1 = gen.compute_cache_key(&config, &hashes).unwrap();
        let k2 = gen.compute_cache_key(&config, &hashes).unwrap();
        assert_eq!(k1, k2);
    }

    #[test]
    fn test_validate_three_part_vlnv() {
        // 3-part VLNV (without version) should be valid
        let gen = VivadoIpGenerator;
        let config: toml::Value = toml::from_str("vlnv = \"xilinx.com:ip:clk_wiz\"").unwrap();
        let diags = gen.validate_config(&config).unwrap();
        assert!(diags.is_empty());
    }

    #[test]
    fn test_validate_five_part_vlnv_invalid() {
        let gen = VivadoIpGenerator;
        let config: toml::Value = toml::from_str("vlnv = \"a:b:c:d:e\"").unwrap();
        let diags = gen.validate_config(&config).unwrap();
        assert!(!diags.is_empty());
        assert!(diags[0].message.contains("Invalid VLNV"));
    }

    #[test]
    fn test_tcl_generation_content() {
        // Execute writes the Tcl file before attempting to run vivado.
        // Even though vivado isn't available, the Tcl file is created.
        let gen = VivadoIpGenerator;
        let tmp = tempfile::TempDir::new().unwrap();
        let output_dir = tmp.path().join("ip_out");

        let config: toml::Value = toml::from_str(&format!(
            r#"
            vlnv = "xilinx.com:ip:clk_wiz:6.0"
            output_dir = "{}"
            [properties]
            CLKOUT1_REQUESTED_OUT_FREQ = "100.0"
            "#,
            output_dir.to_string_lossy().replace('\\', "/")
        ))
        .unwrap();

        let project_manifest: loom_core::manifest::ProjectManifest = toml::from_str(
            r#"
            [project]
            name = "test"
            top_module = "top"
            [target]
            part = "xc7a35t"
            backend = "vivado"
            "#,
        )
        .unwrap();
        let resolved = loom_core::resolve::resolver::ResolvedProject {
            project: project_manifest,
            project_root: tmp.path().to_path_buf(),
            workspace_root: tmp.path().to_path_buf(),
            resolved_components: vec![],
            platform: None,
            active_profile: None,
            variant_selections: std::collections::HashMap::new(),
            profile_params: std::collections::HashMap::new(),
        };
        let context =
            loom_core::build::context::BuildContext::new(resolved, tmp.path().to_path_buf());

        // Will fail with ToolNotFound since vivado isn't installed,
        // but the Tcl file should have been written
        let _result = gen.execute(&config, &context);

        let tcl_path = output_dir.join("clk_wiz_gen.tcl");
        let tcl_content = std::fs::read_to_string(&tcl_path).unwrap();

        assert!(tcl_content.contains("create_ip -vlnv xilinx.com:ip:clk_wiz:6.0"));
        assert!(tcl_content.contains("-module_name clk_wiz"));
        assert!(tcl_content.contains("CONFIG.CLKOUT1_REQUESTED_OUT_FREQ"));
        assert!(tcl_content.contains("{100.0}"));
        assert!(tcl_content.contains("generate_target all [get_ips clk_wiz]"));
    }

    #[test]
    fn test_tcl_config_escape_hatch() {
        let gen = VivadoIpGenerator;
        let tmp = tempfile::TempDir::new().unwrap();
        let output_dir = tmp.path().join("ip_out");

        let config: toml::Value = toml::from_str(&format!(
            r#"
            vlnv = "xilinx.com:ip:axi_bram:4.1"
            output_dir = "{}"
            tcl_config = "custom_config.tcl"
            "#,
            output_dir.to_string_lossy().replace('\\', "/")
        ))
        .unwrap();

        let project_manifest: loom_core::manifest::ProjectManifest = toml::from_str(
            r#"
            [project]
            name = "test"
            top_module = "top"
            [target]
            part = "xc7a35t"
            backend = "vivado"
            "#,
        )
        .unwrap();
        let resolved = loom_core::resolve::resolver::ResolvedProject {
            project: project_manifest,
            project_root: tmp.path().to_path_buf(),
            workspace_root: tmp.path().to_path_buf(),
            resolved_components: vec![],
            platform: None,
            active_profile: None,
            variant_selections: std::collections::HashMap::new(),
            profile_params: std::collections::HashMap::new(),
        };
        let context =
            loom_core::build::context::BuildContext::new(resolved, tmp.path().to_path_buf());

        let _result = gen.execute(&config, &context);

        let tcl_path = output_dir.join("axi_bram_gen.tcl");
        let tcl_content = std::fs::read_to_string(&tcl_path).unwrap();

        assert!(
            tcl_content.contains("source custom_config.tcl"),
            "tcl_config escape hatch not found in: {}",
            tcl_content
        );
    }

    #[test]
    fn test_cache_key_includes_tool_version() {
        let gen = VivadoIpGenerator;
        let config1: toml::Value = toml::from_str(
            r#"
            vlnv = "xilinx.com:ip:clk_wiz:6.0"
            tool_version = "2023.1"
            "#,
        )
        .unwrap();
        let config2: toml::Value = toml::from_str(
            r#"
            vlnv = "xilinx.com:ip:clk_wiz:6.0"
            tool_version = "2024.1"
            "#,
        )
        .unwrap();
        let hashes = HashMap::new();
        let k1 = gen.compute_cache_key(&config1, &hashes).unwrap();
        let k2 = gen.compute_cache_key(&config2, &hashes).unwrap();
        assert_ne!(k1, k2);
    }

    #[test]
    fn test_cache_key_changes_with_properties() {
        let gen = VivadoIpGenerator;
        let config1: toml::Value = toml::from_str(
            r#"
            vlnv = "xilinx.com:ip:clk_wiz:6.0"
            [properties]
            CLKOUT1_REQUESTED_OUT_FREQ = "100.0"
            "#,
        )
        .unwrap();
        let config2: toml::Value = toml::from_str(
            r#"
            vlnv = "xilinx.com:ip:clk_wiz:6.0"
            [properties]
            CLKOUT1_REQUESTED_OUT_FREQ = "200.0"
            "#,
        )
        .unwrap();
        let hashes = HashMap::new();
        let k1 = gen.compute_cache_key(&config1, &hashes).unwrap();
        let k2 = gen.compute_cache_key(&config2, &hashes).unwrap();
        assert_ne!(k1, k2);
    }
}
