use std::path::{Path, PathBuf};

use loom_core::assemble::fileset::{AssembledFile, FileLanguage};
use loom_core::error::LoomError;

/// Generate a Tcl script for out-of-context synthesis of a single component.
pub fn generate_ooc_tcl(
    component_name: &str,
    ooc_top: &str,
    part: &str,
    files: &[AssembledFile],
    output_dir: &Path,
) -> Result<OocScript, LoomError> {
    let mut tcl = String::new();

    tcl.push_str(&format!(
        "# OOC synthesis for component: {}\n",
        component_name
    ));
    tcl.push_str("# Generated by loom — do not edit\n\n");

    // Create in-memory project
    tcl.push_str(&format!("create_project -in_memory -part {{{}}}\n", part));
    tcl.push_str("set_property target_language SystemVerilog [current_project]\n\n");

    // Read source files
    for file in files {
        let path_str = file.path.display().to_string().replace('\\', "/");
        match file.language {
            FileLanguage::SystemVerilog => {
                tcl.push_str(&format!("read_verilog -sv {{{}}}\n", path_str));
            }
            FileLanguage::Verilog => {
                tcl.push_str(&format!("read_verilog {{{}}}\n", path_str));
            }
            FileLanguage::Vhdl => {
                tcl.push_str(&format!("read_vhdl {{{}}}\n", path_str));
            }
            FileLanguage::Unknown => {
                tcl.push_str(&format!("# Skipping unknown file type: {}\n", path_str));
            }
        }
    }

    tcl.push('\n');

    // OOC synthesis
    tcl.push_str(&format!(
        "synth_design -mode out_of_context -top {{{}}} -part {{{}}}\n",
        ooc_top, part
    ));

    // Write checkpoint
    let dcp_path = output_dir.join("post_ooc_synth.dcp");
    let dcp_str = dcp_path.display().to_string().replace('\\', "/");
    tcl.push_str(&format!("write_checkpoint -force {{{}}}\n", dcp_str));

    // Write utilization report
    let rpt_path = output_dir.join("ooc_utilization.rpt");
    let rpt_str = rpt_path.display().to_string().replace('\\', "/");
    tcl.push_str(&format!("report_utilization -file {{{}}}\n", rpt_str));

    let script_path = output_dir.join("ooc_synth.tcl");

    Ok(OocScript {
        tcl_content: tcl,
        script_path,
        dcp_path,
        component_name: component_name.to_string(),
    })
}

/// An OOC synthesis script ready for execution.
#[derive(Debug, Clone)]
pub struct OocScript {
    pub tcl_content: String,
    pub script_path: PathBuf,
    pub dcp_path: PathBuf,
    pub component_name: String,
}

impl OocScript {
    /// Write the Tcl script to disk.
    pub fn write(&self) -> Result<(), LoomError> {
        if let Some(parent) = self.script_path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| LoomError::Io {
                path: parent.to_owned(),
                source: e,
            })?;
        }
        std::fs::write(&self.script_path, &self.tcl_content).map_err(|e| LoomError::Io {
            path: self.script_path.clone(),
            source: e,
        })
    }
}

/// Generate Tcl to load OOC checkpoints in the top-level synthesis.
pub fn generate_read_checkpoints_tcl(ooc_scripts: &[OocScript]) -> String {
    let mut tcl = String::new();
    if ooc_scripts.is_empty() {
        return tcl;
    }

    tcl.push_str("# Load OOC synthesis checkpoints\n");
    for script in ooc_scripts {
        let dcp_str = script.dcp_path.display().to_string().replace('\\', "/");
        tcl.push_str(&format!("read_checkpoint {{{}}}\n", dcp_str));
    }
    tcl.push('\n');

    tcl
}

/// Compute a cache key for OOC synthesis.
pub fn compute_ooc_cache_key(
    component_name: &str,
    file_hashes: &[(String, String)],
    part: &str,
    tool_version: &str,
) -> String {
    use sha2::{Digest, Sha256};

    let mut hasher = Sha256::new();
    hasher.update(b"ooc:");
    hasher.update(component_name.as_bytes());
    hasher.update(b":");
    hasher.update(part.as_bytes());
    hasher.update(b":");
    hasher.update(tool_version.as_bytes());
    for (name, hash) in file_hashes {
        hasher.update(b":");
        hasher.update(name.as_bytes());
        hasher.update(b"=");
        hasher.update(hash.as_bytes());
    }
    hex::encode(hasher.finalize())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_ooc_tcl() {
        let files = vec![
            AssembledFile {
                path: PathBuf::from("/src/ctrl.sv"),
                source_component: "org/ctrl".to_string(),
                language: FileLanguage::SystemVerilog,
            },
            AssembledFile {
                path: PathBuf::from("/src/common.v"),
                source_component: "org/common".to_string(),
                language: FileLanguage::Verilog,
            },
        ];

        let output_dir = PathBuf::from("/build/ooc/ctrl");
        let script =
            generate_ooc_tcl("org/ctrl", "ctrl_wrapper", "xc7a35t", &files, &output_dir).unwrap();

        assert!(script
            .tcl_content
            .contains("synth_design -mode out_of_context"));
        assert!(script.tcl_content.contains("ctrl_wrapper"));
        assert!(script.tcl_content.contains("xc7a35t"));
        assert!(script.tcl_content.contains("read_verilog -sv"));
        assert!(script.tcl_content.contains("read_verilog {/src/common.v}"));
        assert!(script.tcl_content.contains("write_checkpoint"));
    }

    #[test]
    fn test_read_checkpoints_tcl() {
        let scripts = vec![
            OocScript {
                tcl_content: String::new(),
                script_path: PathBuf::from("/build/ooc/a/ooc_synth.tcl"),
                dcp_path: PathBuf::from("/build/ooc/a/post_ooc_synth.dcp"),
                component_name: "org/a".to_string(),
            },
            OocScript {
                tcl_content: String::new(),
                script_path: PathBuf::from("/build/ooc/b/ooc_synth.tcl"),
                dcp_path: PathBuf::from("/build/ooc/b/post_ooc_synth.dcp"),
                component_name: "org/b".to_string(),
            },
        ];

        let tcl = generate_read_checkpoints_tcl(&scripts);
        assert!(tcl.contains("read_checkpoint"));
        assert!(tcl.contains("post_ooc_synth.dcp"));
    }

    #[test]
    fn test_empty_checkpoints() {
        let tcl = generate_read_checkpoints_tcl(&[]);
        assert!(tcl.is_empty());
    }

    #[test]
    fn test_ooc_cache_key_deterministic() {
        let hashes = vec![
            ("file1.sv".to_string(), "abc123".to_string()),
            ("file2.sv".to_string(), "def456".to_string()),
        ];
        let key1 = compute_ooc_cache_key("org/ctrl", &hashes, "xc7a35t", "2023.2");
        let key2 = compute_ooc_cache_key("org/ctrl", &hashes, "xc7a35t", "2023.2");
        assert_eq!(key1, key2);
    }

    #[test]
    fn test_ooc_cache_key_changes_with_part() {
        let hashes = vec![("file1.sv".to_string(), "abc123".to_string())];
        let key1 = compute_ooc_cache_key("org/ctrl", &hashes, "xc7a35t", "2023.2");
        let key2 = compute_ooc_cache_key("org/ctrl", &hashes, "xczu7ev", "2023.2");
        assert_ne!(key1, key2);
    }
}
