use std::fmt::Write as FmtWrite;
use std::path::{Path, PathBuf};

use loom_core::assemble::fileset::{AssembledFilesets, ConstraintScope, FileLanguage};
use loom_core::build::context::BuildContext;
use loom_core::resolve::resolver::ResolvedProject;

/// Generate Vivado non-project-mode Tcl script.
pub fn generate_tcl(
    project: &ResolvedProject,
    filesets: &AssembledFilesets,
    context: &BuildContext,
) -> Result<String, Box<dyn std::error::Error>> {
    let target = project
        .project
        .target
        .as_ref()
        .ok_or("No [target] block in project manifest")?;

    let top_module = &project.project.project.top_module;
    let part = &target.part;

    let bitstream_path = context.build_dir.join(format!("{}.bit", top_module));

    let mut script = String::new();

    // Header
    writeln!(script, "# Auto-generated by Loom -- do not edit")?;
    writeln!(script, "# Project: {}", project.project.project.name)?;
    writeln!(script, "# Part: {}", part)?;
    writeln!(script, "# Generated: {}", chrono::Utc::now().to_rfc3339())?;
    writeln!(script)?;

    // Read source files
    writeln!(script, "# Read source files (dependency order)")?;
    for file in &filesets.synth_files {
        let tcl_path = to_tcl_path(&file.path);
        let cmd = match file.language {
            FileLanguage::SystemVerilog => format!("read_verilog -sv {{{}}}", tcl_path),
            FileLanguage::Verilog => format!("read_verilog {{{}}}", tcl_path),
            FileLanguage::Vhdl => {
                format!("read_vhdl -library work {{{}}}", tcl_path)
            }
            FileLanguage::Unknown => {
                format!(
                    "# WARNING: Unrecognized file type -- skipping: {}",
                    tcl_path
                )
            }
        };
        writeln!(script, "{}", cmd)?;
    }
    writeln!(script)?;

    // Preprocessor defines
    if !filesets.defines.is_empty() {
        writeln!(script, "# Preprocessor defines")?;
        let defines_str = filesets
            .defines
            .iter()
            .map(|d| format!("{{{}}}", d))
            .collect::<Vec<_>>()
            .join(" ");
        writeln!(
            script,
            "set_property verilog_define {} [current_fileset]",
            defines_str
        )?;
        writeln!(script)?;
    }

    // Read constraints
    if !filesets.constraint_files.is_empty() {
        writeln!(
            script,
            "# Read constraints (component-scoped first, then global)"
        )?;
        for constraint in &filesets.constraint_files {
            let tcl_path = to_tcl_path(&constraint.path);
            let cmd = match &constraint.scope {
                ConstraintScope::Component { ref_name } => {
                    format!("read_xdc -ref {} {{{}}}", ref_name, tcl_path)
                }
                ConstraintScope::Global => {
                    format!("read_xdc {{{}}}", tcl_path)
                }
            };
            writeln!(script, "{}", cmd)?;
        }
        writeln!(script)?;
    }

    // Synthesis
    writeln!(script, "# Synthesis")?;
    writeln!(script, "synth_design -top {} -part {}", top_module, part)?;
    writeln!(script)?;

    // Implementation
    writeln!(script, "# Implementation")?;
    writeln!(script, "opt_design")?;
    writeln!(script, "place_design")?;
    writeln!(script, "route_design")?;
    writeln!(script)?;

    // Bitstream
    writeln!(script, "# Bitstream")?;
    writeln!(
        script,
        "write_bitstream -force {{{}}}",
        to_tcl_path(&bitstream_path)
    )?;

    Ok(script)
}

/// Convert a path to Tcl-safe format (forward slashes on all platforms).
pub fn to_tcl_path(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

/// Write the Tcl script to the build directory.
pub fn write_tcl_script(
    script: &str,
    context: &BuildContext,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
    std::fs::create_dir_all(&context.build_dir)?;
    let script_path = context.build_dir.join("build.tcl");
    std::fs::write(&script_path, script)?;
    Ok(script_path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use loom_core::assemble::fileset::{
        AssembledConstraint, AssembledFile, AssembledFilesets, ConstraintScope, FileLanguage,
    };
    use loom_core::resolve::resolver::{
        resolve_project, ResolvedProject, WorkspaceDependencySource,
    };
    use loom_core::resolve::workspace::{
        discover_members, find_project, find_workspace_root, load_all_components,
    };

    fn resolve_simple_project() -> ResolvedProject {
        let fixture = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../tests/fixtures/simple_project");
        let (root, ws_manifest) = find_workspace_root(&fixture).unwrap();
        let members = discover_members(&root, &ws_manifest).unwrap();
        let all_components = load_all_components(&members).unwrap();
        let (project_root, project_manifest) = find_project(&members, None).unwrap();
        let source = WorkspaceDependencySource::new(all_components);
        resolve_project(project_manifest, project_root, root, &source).unwrap()
    }

    #[test]
    fn test_tcl_path_forward_slashes() {
        let path = PathBuf::from(r"C:\tools\Xilinx\test.xdc");
        let tcl_path = to_tcl_path(&path);
        assert!(!tcl_path.contains('\\'));
        assert!(tcl_path.contains('/'));
    }

    #[test]
    fn test_tcl_sv_file() {
        let filesets = AssembledFilesets {
            synth_files: vec![AssembledFile {
                path: PathBuf::from("/workspace/lib/axi_common/rtl/axi_pkg.sv"),
                source_component: "org/axi_common".to_string(),
                language: FileLanguage::SystemVerilog,
            }],
            constraint_files: vec![],
            defines: vec![],
        };

        let resolved = resolve_simple_project();
        let context = BuildContext::new(resolved.clone(), resolved.workspace_root.clone());
        let script = generate_tcl(&resolved, &filesets, &context).unwrap();
        assert!(script.contains("read_verilog -sv {/workspace/lib/axi_common/rtl/axi_pkg.sv}"));
    }

    #[test]
    fn test_tcl_component_scoped_constraint() {
        let filesets = AssembledFilesets {
            synth_files: vec![],
            constraint_files: vec![AssembledConstraint {
                path: PathBuf::from("/workspace/lib/fifo/cdc.xdc"),
                source_component: "org/fifo".to_string(),
                scope: ConstraintScope::Component {
                    ref_name: "fifo".to_string(),
                },
            }],
            defines: vec![],
        };

        let resolved = resolve_simple_project();
        let context = BuildContext::new(resolved.clone(), resolved.workspace_root.clone());
        let script = generate_tcl(&resolved, &filesets, &context).unwrap();
        assert!(script.contains("read_xdc -ref fifo {/workspace/lib/fifo/cdc.xdc}"));
    }

    #[test]
    fn test_tcl_global_constraint() {
        let filesets = AssembledFilesets {
            synth_files: vec![],
            constraint_files: vec![AssembledConstraint {
                path: PathBuf::from("/workspace/constraints/timing.xdc"),
                source_component: "project".to_string(),
                scope: ConstraintScope::Global,
            }],
            defines: vec![],
        };

        let resolved = resolve_simple_project();
        let context = BuildContext::new(resolved.clone(), resolved.workspace_root.clone());
        let script = generate_tcl(&resolved, &filesets, &context).unwrap();
        assert!(script.contains("read_xdc {/workspace/constraints/timing.xdc}"));
        assert!(!script.contains("-ref"));
    }

    #[test]
    fn test_full_script_structure() {
        let resolved = resolve_simple_project();
        let filesets = loom_core::assemble::assemble_filesets(&resolved).unwrap();
        let context = BuildContext::new(resolved.clone(), resolved.workspace_root.clone());
        let script = generate_tcl(&resolved, &filesets, &context).unwrap();

        // Check sections exist in correct order
        let read_idx = script.find("read_verilog").unwrap();
        let xdc_idx = script.find("read_xdc").unwrap();
        let synth_idx = script.find("synth_design").unwrap();
        let opt_idx = script.find("opt_design").unwrap();
        let place_idx = script.find("place_design").unwrap();
        let route_idx = script.find("route_design").unwrap();
        let bit_idx = script.find("write_bitstream").unwrap();

        assert!(read_idx < xdc_idx, "read_verilog before read_xdc");
        assert!(xdc_idx < synth_idx, "read_xdc before synth_design");
        assert!(synth_idx < opt_idx);
        assert!(opt_idx < place_idx);
        assert!(place_idx < route_idx);
        assert!(route_idx < bit_idx);

        // Check synth_design has correct part
        assert!(script.contains("synth_design -top top -part xczu7ev-ffvc1156-2-e"));
    }
}
