use std::fmt::Write as FmtWrite;
use std::path::{Path, PathBuf};

use loom_core::assemble::fileset::{AssembledFilesets, ConstraintScope, FileLanguage};
use loom_core::build::context::BuildContext;
use loom_core::manifest::project::ReportConfig;
use loom_core::resolve::resolver::ResolvedProject;

/// Generate Vivado non-project-mode Tcl script.
pub fn generate_tcl(
    project: &ResolvedProject,
    filesets: &AssembledFilesets,
    context: &BuildContext,
) -> Result<String, Box<dyn std::error::Error>> {
    let target = project
        .project
        .target
        .as_ref()
        .ok_or("No [target] block in project manifest")?;

    let top_module = &project.project.project.top_module;
    let part = &target.part;

    let bitstream_path = context.build_dir.join(format!("{}.bit", top_module));

    let mut script = String::new();

    // Header
    writeln!(script, "# Auto-generated by Loom -- do not edit")?;
    writeln!(script, "# Project: {}", project.project.project.name)?;
    writeln!(script, "# Part: {}", part)?;
    writeln!(script, "# Generated: {}", chrono::Utc::now().to_rfc3339())?;
    writeln!(script)?;

    // Read source files
    if !filesets.synth_files.is_empty() {
        writeln!(
            script,
            "puts \"LOOM_MARKER:ACTIVITY:Loading source files ({})\"",
            filesets.synth_files.len()
        )?;
    }
    writeln!(script, "# Read source files (dependency order)")?;
    for file in &filesets.synth_files {
        let tcl_path = to_tcl_path(&file.path);
        let cmd = match file.language {
            FileLanguage::SystemVerilog => format!("read_verilog -sv {{{}}}", tcl_path),
            FileLanguage::Verilog => format!("read_verilog {{{}}}", tcl_path),
            FileLanguage::Vhdl => {
                format!("read_vhdl -library work {{{}}}", tcl_path)
            }
            FileLanguage::Unknown => {
                format!(
                    "# WARNING: Unrecognized file type -- skipping: {}",
                    tcl_path
                )
            }
        };
        writeln!(script, "{}", cmd)?;
    }
    if !filesets.synth_files.is_empty() {
        writeln!(script, "puts \"LOOM_MARKER:ACTIVITY_DONE\"")?;
    }
    writeln!(script)?;

    // Preprocessor defines
    if !filesets.defines.is_empty() {
        writeln!(script, "# Preprocessor defines")?;
        let defines_str = filesets
            .defines
            .iter()
            .map(|d| format!("{{{}}}", d))
            .collect::<Vec<_>>()
            .join(" ");
        writeln!(
            script,
            "set_property verilog_define {} [current_fileset]",
            defines_str
        )?;
        writeln!(script)?;
    }

    // Read constraints
    if !filesets.constraint_files.is_empty() {
        writeln!(script, "puts \"LOOM_MARKER:ACTIVITY:Loading constraints\"")?;
        writeln!(
            script,
            "# Read constraints (component-scoped first, then global)"
        )?;
        for constraint in &filesets.constraint_files {
            let tcl_path = to_tcl_path(&constraint.path);
            let cmd = match &constraint.scope {
                ConstraintScope::Component { ref_name } => {
                    format!("read_xdc -ref {} {{{}}}", ref_name, tcl_path)
                }
                ConstraintScope::Global => {
                    format!("read_xdc {{{}}}", tcl_path)
                }
            };
            writeln!(script, "{}", cmd)?;
        }
        writeln!(script, "puts \"LOOM_MARKER:ACTIVITY_DONE\"")?;
        writeln!(script)?;
    }

    // Extract report and checkpoint configuration
    let report_cfg = context
        .project
        .project
        .build
        .as_ref()
        .and_then(|b| b.reports.as_ref())
        .cloned()
        .unwrap_or_default();
    let checkpoint_cfg = context
        .project
        .project
        .build
        .as_ref()
        .and_then(|b| b.checkpoints.as_ref())
        .cloned()
        .unwrap_or_default();

    let build_dir_tcl = to_tcl_path(&context.build_dir);

    // Synthesis
    writeln!(script, "# Synthesis")?;
    writeln!(script, "synth_design -top {} -part {}", top_module, part)?;
    writeln!(script)?;

    // Post-synthesis utilization report (stdout capture for live display)
    writeln!(script, "# Post-synthesis utilization")?;
    writeln!(script, "puts \"LOOM_MARKER:REPORT_UTIL_BEGIN\"")?;
    writeln!(script, "report_utilization -no_primitives")?;
    writeln!(script, "puts \"LOOM_MARKER:REPORT_UTIL_END\"")?;
    writeln!(script)?;

    // Post-synthesis report files
    write_report_files_with_activity(&mut script, &report_cfg, &build_dir_tcl, "synth")?;

    // Post-synthesis checkpoint
    if checkpoint_cfg.post_synth() {
        writeln!(
            script,
            "puts \"LOOM_MARKER:ACTIVITY:Saving post-synthesis checkpoint\""
        )?;
        writeln!(
            script,
            "write_checkpoint -force {{{}/post_synth.dcp}}",
            build_dir_tcl
        )?;
        writeln!(script, "puts \"LOOM_MARKER:ACTIVITY_DONE\"")?;
        writeln!(script)?;
    }

    // Implementation
    writeln!(script, "# Implementation")?;
    writeln!(script, "opt_design")?;

    // Post-opt checkpoint
    if checkpoint_cfg.post_opt() {
        writeln!(
            script,
            "puts \"LOOM_MARKER:ACTIVITY:Saving post-optimization checkpoint\""
        )?;
        writeln!(
            script,
            "write_checkpoint -force {{{}/post_opt.dcp}}",
            build_dir_tcl
        )?;
        writeln!(script, "puts \"LOOM_MARKER:ACTIVITY_DONE\"")?;
    }

    writeln!(script, "place_design")?;
    writeln!(script)?;

    // Post-placement timing estimate (stdout capture for live display)
    writeln!(script, "# Post-placement timing estimate")?;
    writeln!(script, "puts \"LOOM_MARKER:POST_PLACE_TIMING_BEGIN\"")?;
    writeln!(script, "report_timing_summary -no_header")?;
    writeln!(script, "puts \"LOOM_MARKER:POST_PLACE_TIMING_END\"")?;
    writeln!(script)?;

    // Post-placement report files
    if report_cfg.timing() {
        writeln!(
            script,
            "puts \"LOOM_MARKER:ACTIVITY:Writing post-placement reports\""
        )?;
        writeln!(
            script,
            "report_timing_summary -file {{{}/timing_place.rpt}}",
            build_dir_tcl
        )?;
        writeln!(script, "puts \"LOOM_MARKER:ACTIVITY_DONE\"")?;
        writeln!(script)?;
    }

    // Post-place checkpoint
    if checkpoint_cfg.post_place() {
        writeln!(
            script,
            "puts \"LOOM_MARKER:ACTIVITY:Saving post-placement checkpoint\""
        )?;
        writeln!(
            script,
            "write_checkpoint -force {{{}/post_place.dcp}}",
            build_dir_tcl
        )?;
        writeln!(script, "puts \"LOOM_MARKER:ACTIVITY_DONE\"")?;
        writeln!(script)?;
    }

    writeln!(script, "route_design")?;
    writeln!(script)?;

    // Post-route timing (final, stdout capture for live display)
    writeln!(script, "# Post-route timing")?;
    writeln!(script, "puts \"LOOM_MARKER:POST_ROUTE_TIMING_BEGIN\"")?;
    writeln!(script, "report_timing_summary -no_header")?;
    writeln!(script, "puts \"LOOM_MARKER:POST_ROUTE_TIMING_END\"")?;
    writeln!(script)?;

    // Post-route report files
    write_report_files_with_activity(&mut script, &report_cfg, &build_dir_tcl, "route")?;

    // Post-route checkpoint
    if checkpoint_cfg.post_route() {
        writeln!(
            script,
            "puts \"LOOM_MARKER:ACTIVITY:Saving post-route checkpoint\""
        )?;
        writeln!(
            script,
            "write_checkpoint -force {{{}/post_route.dcp}}",
            build_dir_tcl
        )?;
        writeln!(script, "puts \"LOOM_MARKER:ACTIVITY_DONE\"")?;
        writeln!(script)?;
    }

    // Bitstream
    writeln!(script, "# Bitstream")?;
    writeln!(
        script,
        "write_bitstream -force {{{}}}",
        to_tcl_path(&bitstream_path)
    )?;

    Ok(script)
}

/// Write report file commands wrapped with activity markers for progress display.
fn write_report_files_with_activity(
    script: &mut String,
    report_cfg: &ReportConfig,
    build_dir_tcl: &str,
    stage: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let has_reports =
        report_cfg.utilization() || report_cfg.timing() || report_cfg.power() || report_cfg.drc();
    if !has_reports {
        return Ok(());
    }
    let label = stage.replace("_", "-");
    writeln!(
        script,
        "puts \"LOOM_MARKER:ACTIVITY:Writing post-{} reports\"",
        label
    )?;
    write_report_files(script, report_cfg, build_dir_tcl, stage)?;
    writeln!(script, "puts \"LOOM_MARKER:ACTIVITY_DONE\"")?;
    writeln!(script)?;
    Ok(())
}

/// Write report file commands based on the report configuration.
fn write_report_files(
    script: &mut String,
    report_cfg: &ReportConfig,
    build_dir_tcl: &str,
    stage: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    if report_cfg.utilization() {
        writeln!(
            script,
            "report_utilization -file {{{}/utilization_{}.rpt}}",
            build_dir_tcl, stage
        )?;
    }
    if report_cfg.timing() {
        writeln!(
            script,
            "report_timing_summary -file {{{}/timing_{}.rpt}}",
            build_dir_tcl, stage
        )?;
    }
    if report_cfg.power() {
        writeln!(
            script,
            "report_power -file {{{}/power_{}.rpt}}",
            build_dir_tcl, stage
        )?;
    }
    if report_cfg.drc() {
        writeln!(
            script,
            "report_drc -file {{{}/drc_{}.rpt}}",
            build_dir_tcl, stage
        )?;
    }
    Ok(())
}

/// Convert a path to Tcl-safe format (forward slashes, no Windows extended-length prefix).
pub fn to_tcl_path(path: &Path) -> String {
    loom_core::util::to_tool_path(path)
}

/// Write the Tcl script to the build directory.
pub fn write_tcl_script(
    script: &str,
    context: &BuildContext,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
    std::fs::create_dir_all(&context.build_dir)?;
    let script_path = context.build_dir.join("build.tcl");
    std::fs::write(&script_path, script)?;
    Ok(script_path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use loom_core::assemble::fileset::{
        AssembledConstraint, AssembledFile, AssembledFilesets, ConstraintScope, FileLanguage,
    };
    use loom_core::resolve::resolver::{
        resolve_project, ResolvedProject, WorkspaceDependencySource,
    };
    use loom_core::resolve::workspace::{
        discover_members, find_project, find_workspace_root, load_all_components,
    };

    fn resolve_blinky_project() -> ResolvedProject {
        let fixture =
            std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../examples/blinky");
        let (root, ws_manifest) = find_workspace_root(&fixture).unwrap();
        let members = discover_members(&root, &ws_manifest).unwrap();
        let all_components = load_all_components(&members).unwrap();
        let (project_root, project_manifest) = find_project(&members, None).unwrap();
        let source = WorkspaceDependencySource::new(all_components);
        resolve_project(project_manifest, project_root, root, &source).unwrap()
    }

    fn resolve_uart_project() -> ResolvedProject {
        let fixture =
            std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../examples/basys3_uart");
        let (root, ws_manifest) = find_workspace_root(&fixture).unwrap();
        let members = discover_members(&root, &ws_manifest).unwrap();
        let all_components = load_all_components(&members).unwrap();
        let (project_root, project_manifest) = find_project(&members, Some("basys3_uart")).unwrap();
        let source = WorkspaceDependencySource::new(all_components);
        resolve_project(project_manifest, project_root, root, &source).unwrap()
    }

    fn resolve_simple_project() -> ResolvedProject {
        let fixture = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../tests/fixtures/simple_project");
        let (root, ws_manifest) = find_workspace_root(&fixture).unwrap();
        let members = discover_members(&root, &ws_manifest).unwrap();
        let all_components = load_all_components(&members).unwrap();
        let (project_root, project_manifest) = find_project(&members, None).unwrap();
        let source = WorkspaceDependencySource::new(all_components);
        resolve_project(project_manifest, project_root, root, &source).unwrap()
    }

    #[test]
    fn test_tcl_path_forward_slashes() {
        let path = PathBuf::from(r"C:\tools\Xilinx\test.xdc");
        let tcl_path = to_tcl_path(&path);
        assert!(!tcl_path.contains('\\'));
        assert!(tcl_path.contains('/'));
    }

    #[test]
    fn test_tcl_path_strips_extended_length_prefix() {
        // Windows canonicalize() produces \\?\ prefix
        let path = PathBuf::from(r"\\?\Z:\loom\examples\blinky\rtl\counter.sv");
        let tcl_path = to_tcl_path(&path);
        assert_eq!(tcl_path, "Z:/loom/examples/blinky/rtl/counter.sv");
        assert!(!tcl_path.contains("//"));
    }

    #[test]
    fn test_tcl_sv_file() {
        let filesets = AssembledFilesets {
            synth_files: vec![AssembledFile {
                path: PathBuf::from("/workspace/lib/axi_common/rtl/axi_pkg.sv"),
                source_component: "org/axi_common".to_string(),
                language: FileLanguage::SystemVerilog,
            }],
            constraint_files: vec![],
            defines: vec![],
        };

        let resolved = resolve_simple_project();
        let context = BuildContext::new(resolved.clone(), resolved.workspace_root.clone());
        let script = generate_tcl(&resolved, &filesets, &context).unwrap();
        assert!(script.contains("read_verilog -sv {/workspace/lib/axi_common/rtl/axi_pkg.sv}"));
    }

    #[test]
    fn test_tcl_component_scoped_constraint() {
        let filesets = AssembledFilesets {
            synth_files: vec![],
            constraint_files: vec![AssembledConstraint {
                path: PathBuf::from("/workspace/lib/fifo/cdc.xdc"),
                source_component: "org/fifo".to_string(),
                scope: ConstraintScope::Component {
                    ref_name: "fifo".to_string(),
                },
            }],
            defines: vec![],
        };

        let resolved = resolve_simple_project();
        let context = BuildContext::new(resolved.clone(), resolved.workspace_root.clone());
        let script = generate_tcl(&resolved, &filesets, &context).unwrap();
        assert!(script.contains("read_xdc -ref fifo {/workspace/lib/fifo/cdc.xdc}"));
    }

    #[test]
    fn test_tcl_global_constraint() {
        let filesets = AssembledFilesets {
            synth_files: vec![],
            constraint_files: vec![AssembledConstraint {
                path: PathBuf::from("/workspace/constraints/timing.xdc"),
                source_component: "project".to_string(),
                scope: ConstraintScope::Global,
            }],
            defines: vec![],
        };

        let resolved = resolve_simple_project();
        let context = BuildContext::new(resolved.clone(), resolved.workspace_root.clone());
        let script = generate_tcl(&resolved, &filesets, &context).unwrap();
        assert!(script.contains("read_xdc {/workspace/constraints/timing.xdc}"));
        assert!(!script.contains("-ref"));
    }

    #[test]
    fn test_full_script_structure() {
        let resolved = resolve_simple_project();
        let filesets = loom_core::assemble::assemble_filesets(&resolved).unwrap();
        let context = BuildContext::new(resolved.clone(), resolved.workspace_root.clone());
        let script = generate_tcl(&resolved, &filesets, &context).unwrap();

        // Check sections exist in correct order
        let read_idx = script.find("read_verilog").unwrap();
        let xdc_idx = script.find("read_xdc").unwrap();
        let synth_idx = script.find("synth_design").unwrap();
        let opt_idx = script.find("opt_design").unwrap();
        let place_idx = script.find("place_design").unwrap();
        let route_idx = script.find("route_design").unwrap();
        let bit_idx = script.find("write_bitstream").unwrap();

        assert!(read_idx < xdc_idx, "read_verilog before read_xdc");
        assert!(xdc_idx < synth_idx, "read_xdc before synth_design");
        assert!(synth_idx < opt_idx);
        assert!(opt_idx < place_idx);
        assert!(place_idx < route_idx);
        assert!(route_idx < bit_idx);

        // Check synth_design has correct part
        assert!(script.contains("synth_design -top top -part xczu7ev-ffvc1156-2-e"));
    }

    #[test]
    fn test_blinky_demo_tcl_generation() {
        let resolved = resolve_blinky_project();
        let filesets = loom_core::assemble::assemble_filesets(&resolved).unwrap();
        let context = BuildContext::new(resolved.clone(), resolved.workspace_root.clone());
        let script = generate_tcl(&resolved, &filesets, &context).unwrap();

        // Dependency order: counter.sv must appear before blinky.sv
        let counter_idx = script.find("counter.sv").expect("counter.sv in script");
        let blinky_idx = script.find("blinky.sv").expect("blinky.sv in script");
        let top_idx = script.find("top.sv").expect("top.sv in script");
        assert!(
            counter_idx < blinky_idx,
            "counter.sv must come before blinky.sv"
        );
        assert!(blinky_idx < top_idx, "blinky.sv must come before top.sv");

        // Constraint scoping: blinky.xdc is component-scoped, basys3.xdc is global
        assert!(
            script.contains("read_xdc -ref blinky"),
            "blinky.xdc should be component-scoped"
        );
        assert!(
            script.contains("basys3.xdc}"),
            "basys3.xdc should be present"
        );

        // Correct part number
        assert!(
            script.contains("synth_design -top top -part xc7a35tcpg236-1"),
            "Should use Basys 3 part number"
        );
    }

    #[test]
    fn test_report_commands_injected() {
        let resolved = resolve_simple_project();
        let filesets = loom_core::assemble::assemble_filesets(&resolved).unwrap();
        let context = BuildContext::new(resolved.clone(), resolved.workspace_root.clone());
        let script = generate_tcl(&resolved, &filesets, &context).unwrap();

        // Utilization report after synth_design
        assert!(
            script.contains("LOOM_MARKER:REPORT_UTIL_BEGIN"),
            "Should have utilization marker begin"
        );
        assert!(
            script.contains("report_utilization -no_primitives"),
            "Should inject report_utilization"
        );
        assert!(
            script.contains("LOOM_MARKER:REPORT_UTIL_END"),
            "Should have utilization marker end"
        );

        // Post-placement timing
        assert!(
            script.contains("LOOM_MARKER:POST_PLACE_TIMING_BEGIN"),
            "Should have post-place timing marker"
        );
        assert!(
            script.contains("LOOM_MARKER:POST_PLACE_TIMING_END"),
            "Should have post-place timing marker end"
        );

        // Post-route timing
        assert!(
            script.contains("LOOM_MARKER:POST_ROUTE_TIMING_BEGIN"),
            "Should have post-route timing marker"
        );
        assert!(
            script.contains("LOOM_MARKER:POST_ROUTE_TIMING_END"),
            "Should have post-route timing marker end"
        );

        // Timing summary commands: 2 for stdout capture + 3 file reports (synth, place, route)
        let timing_count = script.matches("report_timing_summary").count();
        assert_eq!(
            timing_count, 5,
            "Should have 5 timing summary commands (2 stdout + 3 file)"
        );

        // Report file commands (default config: utilization + timing enabled)
        assert!(
            script.contains("report_utilization -file"),
            "Should have utilization file report"
        );
        assert!(
            script.contains("report_timing_summary -file"),
            "Should have timing file report"
        );

        // Default config: checkpoints for post_place and post_route
        assert!(
            script.contains("write_checkpoint -force"),
            "Should have checkpoint commands"
        );
        let checkpoint_count = script.matches("write_checkpoint").count();
        assert_eq!(
            checkpoint_count, 2,
            "Default config: post_place + post_route checkpoints"
        );

        // Activity markers for source loading, constraints, reports, and checkpoints
        assert!(
            script.contains("LOOM_MARKER:ACTIVITY:Loading source files"),
            "Should have source file loading activity marker"
        );
        assert!(
            script.contains("LOOM_MARKER:ACTIVITY:Loading constraints"),
            "Should have constraint loading activity marker"
        );
        let activity_count = script.matches("LOOM_MARKER:ACTIVITY:").count();
        assert!(
            activity_count >= 6,
            "Should have activity markers for sources, constraints, reports, and checkpoints (got {})",
            activity_count
        );
        let activity_done_count = script.matches("LOOM_MARKER:ACTIVITY_DONE").count();
        assert_eq!(
            activity_count, activity_done_count,
            "Each ACTIVITY should have a matching ACTIVITY_DONE"
        );
    }

    #[test]
    fn test_report_commands_ordering() {
        let resolved = resolve_simple_project();
        let filesets = loom_core::assemble::assemble_filesets(&resolved).unwrap();
        let context = BuildContext::new(resolved.clone(), resolved.workspace_root.clone());
        let script = generate_tcl(&resolved, &filesets, &context).unwrap();

        let synth_idx = script.find("synth_design").unwrap();
        let util_begin_idx = script.find("LOOM_MARKER:REPORT_UTIL_BEGIN").unwrap();
        let util_end_idx = script.find("LOOM_MARKER:REPORT_UTIL_END").unwrap();
        let opt_idx = script.find("opt_design").unwrap();
        let place_idx = script.find("place_design").unwrap();
        let post_place_idx = script.find("LOOM_MARKER:POST_PLACE_TIMING_BEGIN").unwrap();
        let route_idx = script.find("route_design").unwrap();
        let post_route_idx = script.find("LOOM_MARKER:POST_ROUTE_TIMING_BEGIN").unwrap();
        let bit_idx = script.find("write_bitstream").unwrap();

        assert!(synth_idx < util_begin_idx, "util report after synth");
        assert!(util_begin_idx < util_end_idx, "util markers ordered");
        assert!(util_end_idx < opt_idx, "util report before opt");
        assert!(place_idx < post_place_idx, "post-place timing after place");
        assert!(post_place_idx < route_idx, "post-place timing before route");
        assert!(route_idx < post_route_idx, "post-route timing after route");
        assert!(
            post_route_idx < bit_idx,
            "post-route timing before bitstream"
        );
    }

    #[test]
    fn test_uart_demo_tcl_generation() {
        let resolved = resolve_uart_project();
        let filesets = loom_core::assemble::assemble_filesets(&resolved).unwrap();
        let context = BuildContext::new(resolved.clone(), resolved.workspace_root.clone());
        let script = generate_tcl(&resolved, &filesets, &context).unwrap();

        // Dependency ordering: counter.sv must appear before seg7_controller.sv
        let counter_idx = script.find("counter.sv").expect("counter.sv in script");
        let seg7_idx = script
            .find("seg7_controller.sv")
            .expect("seg7_controller.sv in script");
        let top_idx = script.find("top.sv").expect("top.sv in script");
        assert!(
            counter_idx < seg7_idx,
            "counter.sv must come before seg7_controller.sv (dependency order)"
        );
        assert!(
            seg7_idx < top_idx,
            "seg7_controller.sv must come before top.sv"
        );

        // UART files present
        assert!(
            script.contains("uart_tx.sv"),
            "uart_tx.sv should be in script"
        );
        assert!(
            script.contains("uart_rx.sv"),
            "uart_rx.sv should be in script"
        );
        assert!(
            script.contains("cdc_sync.sv"),
            "cdc_sync.sv should be in script"
        );
        assert!(
            script.contains("clk_gen.sv"),
            "clk_gen.sv should be in script"
        );

        // Component-scoped constraint with -ref for clk_gen (module name matches)
        assert!(
            script.contains("read_xdc -ref clk_gen"),
            "clk_gen.xdc should be component-scoped"
        );

        // uart_cdc.xdc is global (no wrapper module, uses hierarchical paths)
        let uart_xdc_line = script
            .lines()
            .find(|l| l.contains("uart_cdc.xdc"))
            .expect("uart_cdc.xdc should be present");
        assert!(
            !uart_xdc_line.contains("-ref"),
            "uart_cdc.xdc should be global (no -ref)"
        );

        // basys3.xdc is global
        let basys3_line = script
            .lines()
            .find(|l| l.contains("basys3.xdc"))
            .expect("basys3.xdc should be present");
        assert!(
            !basys3_line.contains("-ref"),
            "basys3.xdc should be global (no -ref)"
        );

        // Generated clock constraint file is referenced
        assert!(
            script.contains("clk_gen.xdc"),
            "clk_gen.xdc should appear in constraints"
        );

        // Correct part number
        assert!(
            script.contains("synth_design -top top -part xc7a35tcpg236-1"),
            "Should use Basys 3 part number"
        );
    }
}
