#!/usr/bin/env python3
"""Generate FIR filter coefficients as a .mem file for $readmemh.

Usage:
    python3 gen_fir_coeffs.py --order 32 --width 16 --cutoff 0.25 --output coeffs.mem

Requires: scipy, numpy
"""

import argparse
import os
import sys


def quantize_signed(values, width):
    """Quantize float array to signed fixed-point, return as two's complement integers."""
    scale = (1 << (width - 1)) - 1
    qvals = []
    for v in values:
        q = int(round(v * scale))
        q = max(-(1 << (width - 1)), min((1 << (width - 1)) - 1, q))
        if q < 0:
            q += (1 << width)
        qvals.append(q)
    return qvals


def main():
    parser = argparse.ArgumentParser(description="Generate FIR coefficients .mem file")
    parser.add_argument("--order", type=int, default=32, help="Filter order (number of taps)")
    parser.add_argument("--width", type=int, default=16, help="Coefficient bit width")
    parser.add_argument("--cutoff", type=float, default=0.25, help="Normalized cutoff frequency (0..1)")
    parser.add_argument("--output", required=True, help="Output .mem file path")
    args = parser.parse_args()

    try:
        from scipy.signal import firwin
    except ImportError:
        print("Warning: scipy not available, generating rectangular window coefficients", file=sys.stderr)
        # Fallback: simple sinc-based coefficients without windowing
        import math
        n = args.order
        coeffs = []
        for i in range(n):
            x = i - (n - 1) / 2.0
            if abs(x) < 1e-10:
                coeffs.append(2.0 * args.cutoff)
            else:
                coeffs.append(math.sin(2.0 * math.pi * args.cutoff * x) / (math.pi * x))
        # Normalize
        s = sum(coeffs)
        coeffs = [c / s for c in coeffs]
    else:
        coeffs = firwin(args.order, args.cutoff)

    qvals = quantize_signed(coeffs, args.width)

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)

    hex_width = (args.width + 3) // 4
    with open(args.output, "w") as f:
        f.write(f"// FIR coefficients: order={args.order}, width={args.width}, cutoff={args.cutoff}\n")
        f.write(f"// Generated by gen_fir_coeffs.py — DO NOT EDIT\n")
        for i, q in enumerate(qvals):
            f.write(f"{q:0{hex_width}X}\n")

    print(f"  wrote {args.output} ({len(qvals)} coefficients, {args.width}-bit)")


if __name__ == "__main__":
    main()
