use std::path::PathBuf;
use std::process::Command;

use loom_core::assemble::fileset::{AssembledFilesets, FileLanguage};
use loom_core::build::context::BuildContext;
use loom_core::error::LoomError;
use loom_core::plugin::backend::BuildResult;
use loom_core::resolve::resolver::ResolvedProject;

use crate::YosysArchitecture;

/// Generate a yosys synthesis script.
pub fn generate_yosys_script(
    project: &ResolvedProject,
    filesets: &AssembledFilesets,
    arch: &YosysArchitecture,
) -> Result<String, LoomError> {
    let top = &project.project.project.top_module;
    let mut script = String::new();

    script.push_str("# yosys synthesis script\n");
    script.push_str("# Generated by loom — do not edit\n\n");

    // Read source files
    for file in &filesets.synth_files {
        let path_str = file.path.display().to_string().replace('\\', "/");
        match file.language {
            FileLanguage::SystemVerilog => {
                script.push_str(&format!("read_verilog -sv {}\n", path_str));
            }
            FileLanguage::Verilog => {
                script.push_str(&format!("read_verilog {}\n", path_str));
            }
            FileLanguage::Vhdl => {
                script.push_str(&format!("read_vhdl {}\n", path_str));
            }
            FileLanguage::Unknown => {
                script.push_str(&format!("# Skipping unknown file: {}\n", path_str));
            }
        }
    }

    // Defines
    for define in &filesets.defines {
        script.push_str(&format!("verilog_defaults -add -D{}\n", define));
    }

    script.push('\n');

    // Synth command
    script.push_str(&format!(
        "{} -top {} -json design.json\n",
        arch.synth_command(),
        top
    ));

    Ok(script)
}

/// Write yosys script to build dir.
pub fn write_yosys_script(script: &str, context: &BuildContext) -> Result<PathBuf, LoomError> {
    std::fs::create_dir_all(&context.build_dir).map_err(|e| LoomError::Io {
        path: context.build_dir.clone(),
        source: e,
    })?;

    let path = context.build_dir.join("synth.ys");
    std::fs::write(&path, script).map_err(|e| LoomError::Io {
        path: path.clone(),
        source: e,
    })?;

    Ok(path)
}

/// Run yosys with the given script.
pub fn run_yosys(script: &PathBuf, context: &BuildContext) -> Result<BuildResult, LoomError> {
    let log_path = context.build_dir.join("yosys.log");

    let output = Command::new("yosys")
        .arg("-s")
        .arg(script)
        .current_dir(&context.build_dir)
        .output()
        .map_err(|e| LoomError::ToolNotFound {
            tool: "yosys".to_string(),
            message: e.to_string(),
        })?;

    let stdout = String::from_utf8_lossy(&output.stdout);
    let _ = std::fs::write(&log_path, stdout.as_ref());

    let success = output.status.success();

    Ok(BuildResult {
        success,
        exit_code: output.status.code().unwrap_or(-1),
        log_paths: vec![log_path],
        bitstream_path: None,
        phases_completed: if success {
            vec!["synthesis".to_string()]
        } else {
            vec![]
        },
        failure_phase: if !success {
            Some("synthesis".to_string())
        } else {
            None
        },
        failure_message: if !success {
            Some("yosys synthesis failed".to_string())
        } else {
            None
        },
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use loom_core::assemble::fileset::AssembledFile;

    #[test]
    fn test_generate_ice40_script() {
        let project: loom_core::manifest::ProjectManifest = toml::from_str(
            r#"
[project]
name = "blinky"
top_module = "top"
[target]
part = "lp8k"
backend = "yosys"
"#,
        )
        .unwrap();

        let resolved = loom_core::resolve::resolver::ResolvedProject {
            project,
            project_root: PathBuf::from("/project"),
            workspace_root: PathBuf::from("/workspace"),
            resolved_components: vec![],
            platform: None,
            active_profile: None,
            variant_selections: std::collections::HashMap::new(),
        };

        let filesets = AssembledFilesets {
            synth_files: vec![AssembledFile {
                path: PathBuf::from("/project/src/top.v"),
                source_component: "blinky".to_string(),
                language: FileLanguage::Verilog,
            }],
            constraint_files: vec![],
            defines: vec![],
        };

        let script =
            generate_yosys_script(&resolved, &filesets, &YosysArchitecture::Ice40).unwrap();
        assert!(script.contains("read_verilog /project/src/top.v"));
        assert!(script.contains("synth_ice40 -top top -json design.json"));
    }
}
