#!/usr/bin/env python3
"""Generate SystemVerilog register file from JSON register specification.

Usage:
    python3 gen_regmap.py <spec.json> <output_dir/>

Produces two files:
    - <name>_regs_pkg.sv  — address constants, field masks
    - <name>_regs.sv      — register file module with native bus interface
"""

import json
import os
import sys


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <spec.json> <output_dir>", file=sys.stderr)
        sys.exit(1)

    spec_path = sys.argv[1]
    out_dir = sys.argv[2]

    with open(spec_path) as f:
        spec = json.load(f)

    name = spec["name"]
    dw = spec["data_width"]
    aw = spec["addr_width"]
    regs = spec["registers"]

    os.makedirs(out_dir, exist_ok=True)

    # --- Package ---
    pkg_lines = []
    pkg_lines.append(f"// Auto-generated by gen_regmap.py — DO NOT EDIT")
    pkg_lines.append(f"package {name}_regs_pkg;")
    pkg_lines.append(f"")
    pkg_lines.append(f"  localparam int DATA_WIDTH = {dw};")
    pkg_lines.append(f"  localparam int ADDR_WIDTH = {aw};")
    pkg_lines.append(f"")
    for r in regs:
        pkg_lines.append(f"  localparam logic [{aw-1}:0] ADDR_{r['name']} = {aw}'h{int(r['offset'], 16):02X};")
    pkg_lines.append(f"")
    pkg_lines.append(f"endpackage")
    pkg_lines.append(f"")

    pkg_path = os.path.join(out_dir, f"{name}_regs_pkg.sv")
    with open(pkg_path, "w") as f:
        f.write("\n".join(pkg_lines))
    print(f"  wrote {pkg_path}")

    # --- Register file module ---
    mod_lines = []
    mod_lines.append(f"// Auto-generated by gen_regmap.py — DO NOT EDIT")
    mod_lines.append(f"module {name}_regs (")
    mod_lines.append(f"  input  logic                  clk,")
    mod_lines.append(f"  input  logic                  rst_n,")
    mod_lines.append(f"")
    mod_lines.append(f"  // Native bus interface")
    mod_lines.append(f"  input  logic [{aw-1}:0] bus_addr,")
    mod_lines.append(f"  input  logic                  bus_wr,")
    mod_lines.append(f"  input  logic                  bus_rd,")
    mod_lines.append(f"  input  logic [{dw-1}:0] bus_wdata,")
    mod_lines.append(f"  output logic [{dw-1}:0] bus_rdata,")
    mod_lines.append(f"  output logic                  bus_ready,")
    mod_lines.append(f"")

    # Hardware ports for each register
    for r in regs:
        rname = r["name"].lower()
        access = r["access"]
        if access in ("RW", "W1C"):
            mod_lines.append(f"  output logic [{dw-1}:0] hw_{rname},")
        if access == "RO":
            mod_lines.append(f"  input  logic [{dw-1}:0] hw_{rname},")

    # Remove trailing comma from last port
    last = mod_lines[-1]
    if last.endswith(","):
        mod_lines[-1] = last[:-1]

    mod_lines.append(f");")
    mod_lines.append(f"")

    # Address constants (inline, yosys-compatible)
    for r in regs:
        mod_lines.append(f"  localparam logic [{aw-1}:0] ADDR_{r['name']} = {aw}'h{int(r['offset'], 16):02X};")
    mod_lines.append(f"")

    # Register storage for RW and W1C registers
    rw_regs = [r for r in regs if r["access"] in ("RW", "W1C")]
    for r in rw_regs:
        rname = r["name"].lower()
        mod_lines.append(f"  logic [{dw-1}:0] reg_{rname};")
    mod_lines.append(f"")

    # Assign hw_ outputs from register storage
    for r in rw_regs:
        rname = r["name"].lower()
        mod_lines.append(f"  assign hw_{rname} = reg_{rname};")
    mod_lines.append(f"")

    # Write decode
    mod_lines.append(f"  // Write decode")
    mod_lines.append(f"  always_ff @(posedge clk or negedge rst_n) begin")
    mod_lines.append(f"    if (!rst_n) begin")
    for r in rw_regs:
        rname = r["name"].lower()
        reset_val = f"{dw}'h{int(r['reset'], 16):08X}"
        mod_lines.append(f"      reg_{rname} <= {reset_val};")
    mod_lines.append(f"    end else if (bus_wr) begin")
    mod_lines.append(f"      case (bus_addr)")
    for r in regs:
        rname = r["name"].lower()
        access = r["access"]
        if access == "RW":
            mod_lines.append(f"        ADDR_{r['name']}: reg_{rname} <= bus_wdata;")
        elif access == "W1C":
            mod_lines.append(f"        ADDR_{r['name']}: reg_{rname} <= reg_{rname} & ~bus_wdata;")
    mod_lines.append(f"        default: ;")
    mod_lines.append(f"      endcase")
    mod_lines.append(f"    end")
    mod_lines.append(f"  end")
    mod_lines.append(f"")

    # Read mux
    mod_lines.append(f"  // Read mux")
    mod_lines.append(f"  always_comb begin")
    mod_lines.append(f"    bus_rdata = {dw}'h0;")
    mod_lines.append(f"    if (bus_rd) begin")
    mod_lines.append(f"      case (bus_addr)")
    for r in regs:
        rname = r["name"].lower()
        access = r["access"]
        if access == "RO":
            mod_lines.append(f"        ADDR_{r['name']}: bus_rdata = hw_{rname};")
        else:
            mod_lines.append(f"        ADDR_{r['name']}: bus_rdata = reg_{rname};")
    mod_lines.append(f"        default: bus_rdata = {dw}'h0;")
    mod_lines.append(f"      endcase")
    mod_lines.append(f"    end")
    mod_lines.append(f"  end")
    mod_lines.append(f"")

    # Ready is always asserted (single-cycle access)
    mod_lines.append(f"  assign bus_ready = 1'b1;")
    mod_lines.append(f"")
    mod_lines.append(f"endmodule")
    mod_lines.append(f"")

    mod_path = os.path.join(out_dir, f"{name}_regs.sv")
    with open(mod_path, "w") as f:
        f.write("\n".join(mod_lines))
    print(f"  wrote {mod_path}")


if __name__ == "__main__":
    main()
