use std::collections::HashMap;
use std::path::PathBuf;

use sha2::{Digest, Sha256};

use loom_core::build::context::BuildContext;
use loom_core::error::LoomError;
use loom_core::plugin::backend::Diagnostic;
use loom_core::plugin::generator::{GeneratorPlugin, GeneratorResult};

/// Generator plugin for Quartus/Platform Designer IP instantiation.
///
/// Generates Tcl scripts or `.ip` parameter files for qsys-generate.
pub struct QuartusIpGenerator;

impl GeneratorPlugin for QuartusIpGenerator {
    fn plugin_name(&self) -> &str {
        "quartus_ip"
    }

    fn check_environment(&self) -> Result<Vec<Diagnostic>, LoomError> {
        match std::process::Command::new("qsys-generate")
            .arg("--version")
            .output()
        {
            Ok(output) if output.status.success() => Ok(vec![]),
            _ => Ok(vec![Diagnostic {
                severity: loom_core::plugin::backend::DiagnosticSeverity::Error,
                message:
                    "Quartus tools not found on PATH. Install Intel Quartus Prime and add to PATH."
                        .to_string(),
                source_path: None,
                line: None,
            }]),
        }
    }

    fn validate_config(&self, config: &toml::Value) -> Result<Vec<Diagnostic>, LoomError> {
        let mut diagnostics = Vec::new();

        if config.get("ip_name").and_then(|v| v.as_str()).is_none() {
            diagnostics.push(Diagnostic {
                severity: loom_core::plugin::backend::DiagnosticSeverity::Error,
                message: "quartus_ip generator requires 'ip_name' field".to_string(),
                source_path: None,
                line: None,
            });
        }

        Ok(diagnostics)
    }

    fn compute_cache_key(
        &self,
        config: &toml::Value,
        input_hashes: &HashMap<String, String>,
    ) -> Result<String, LoomError> {
        let mut hasher = Sha256::new();
        hasher.update(b"quartus_ip\0");

        if let Some(ip_name) = config.get("ip_name").and_then(|v| v.as_str()) {
            hasher.update(ip_name.as_bytes());
        }
        hasher.update(b"\0");

        // Include properties in cache key
        if let Some(props) = config.get("properties").and_then(|v| v.as_table()) {
            let mut sorted: Vec<_> = props.iter().collect();
            sorted.sort_by_key(|(k, _)| k.as_str());
            for (k, v) in sorted {
                hasher.update(k.as_bytes());
                hasher.update(b"=");
                hasher.update(v.to_string().as_bytes());
                hasher.update(b"\0");
            }
        }

        // Include tool version
        if let Some(ver) = config.get("tool_version").and_then(|v| v.as_str()) {
            hasher.update(b"tool_version:");
            hasher.update(ver.as_bytes());
            hasher.update(b"\0");
        }

        // Include input hashes
        let mut sorted: Vec<_> = input_hashes.iter().collect();
        sorted.sort_by_key(|(k, _)| k.as_str());
        for (path, hash) in sorted {
            hasher.update(path.as_bytes());
            hasher.update(b":");
            hasher.update(hash.as_bytes());
            hasher.update(b"\0");
        }

        Ok(hex::encode(hasher.finalize()))
    }

    fn execute(
        &self,
        config: &toml::Value,
        _context: &BuildContext,
    ) -> Result<GeneratorResult, LoomError> {
        let ip_name = config
            .get("ip_name")
            .and_then(|v| v.as_str())
            .ok_or_else(|| {
                LoomError::Internal("quartus_ip: 'ip_name' field is required".to_string())
            })?;

        let output_dir = config
            .get("output_dir")
            .and_then(|v| v.as_str())
            .ok_or_else(|| {
                LoomError::Internal("quartus_ip: 'output_dir' not provided in config".to_string())
            })?;

        // Generate Tcl script for Quartus IP creation
        let mut tcl = String::new();
        tcl.push_str("# Auto-generated by Loom quartus_ip generator\n");
        tcl.push_str("package require -exact qsys 18.0\n\n");
        tcl.push_str(&format!("create_system {}\n", ip_name));

        // Apply properties
        if let Some(props) = config.get("properties").and_then(|v| v.as_table()) {
            for (key, value) in props {
                let val_str = match value {
                    toml::Value::String(s) => s.clone(),
                    other => other.to_string(),
                };
                tcl.push_str(&format!(
                    "set_instance_parameter_value {{{}}} {{{}}} {{{}}}\n",
                    ip_name, key, val_str
                ));
            }
        }

        tcl.push_str(&format!("save_system {}.ip\n", ip_name));

        // Write Tcl script
        let tcl_path = PathBuf::from(output_dir).join(format!("{}_gen.tcl", ip_name));
        std::fs::create_dir_all(output_dir).map_err(|e| LoomError::Io {
            path: PathBuf::from(output_dir),
            source: e,
        })?;
        std::fs::write(&tcl_path, &tcl).map_err(|e| LoomError::Io {
            path: tcl_path.clone(),
            source: e,
        })?;

        // Try to execute qsys-generate
        let qsys_result = std::process::Command::new("qsys-generate")
            .arg(&tcl_path)
            .current_dir(output_dir)
            .output();

        match qsys_result {
            Ok(output) => {
                if !output.status.success() {
                    let stderr = String::from_utf8_lossy(&output.stderr);
                    return Err(LoomError::Internal(format!(
                        "Quartus IP generation failed: {}",
                        stderr.lines().next().unwrap_or("unknown error")
                    )));
                }

                let mut produced = vec![tcl_path];
                let ip_path = PathBuf::from(output_dir).join(format!("{}.ip", ip_name));
                if ip_path.exists() {
                    produced.push(ip_path);
                }

                Ok(GeneratorResult {
                    success: true,
                    produced_files: produced,
                    log: String::from_utf8_lossy(&output.stdout)
                        .lines()
                        .map(String::from)
                        .collect(),
                })
            }
            Err(_) => Err(LoomError::ToolNotFound {
                tool: "qsys-generate".to_string(),
                message: "Quartus tools not found on PATH. Install Quartus and add to PATH."
                    .to_string(),
            }),
        }
    }

    fn clean(&self, config: &toml::Value, _context: &BuildContext) -> Result<(), LoomError> {
        if let Some(output_dir) = config.get("output_dir").and_then(|v| v.as_str()) {
            let path = PathBuf::from(output_dir);
            if path.exists() {
                std::fs::remove_dir_all(&path).map_err(|e| LoomError::Io { path, source: e })?;
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_validate_missing_ip_name() {
        let gen = QuartusIpGenerator;
        let config: toml::Value = toml::from_str("key = \"value\"").unwrap();
        let diags = gen.validate_config(&config).unwrap();
        assert!(!diags.is_empty());
        assert!(diags[0].message.contains("ip_name"));
    }

    #[test]
    fn test_validate_valid_config() {
        let gen = QuartusIpGenerator;
        let config: toml::Value = toml::from_str("ip_name = \"my_pll\"").unwrap();
        let diags = gen.validate_config(&config).unwrap();
        assert!(diags.is_empty());
    }

    #[test]
    fn test_cache_key_deterministic() {
        let gen = QuartusIpGenerator;
        let config: toml::Value = toml::from_str("ip_name = \"my_pll\"").unwrap();
        let hashes = HashMap::new();
        let k1 = gen.compute_cache_key(&config, &hashes).unwrap();
        let k2 = gen.compute_cache_key(&config, &hashes).unwrap();
        assert_eq!(k1, k2);
    }

    #[test]
    fn test_tcl_generation_content() {
        let gen = QuartusIpGenerator;
        let tmp = tempfile::TempDir::new().unwrap();
        let output_dir = tmp.path().join("ip_out");

        let config: toml::Value = toml::from_str(&format!(
            r#"
            ip_name = "my_pll"
            output_dir = "{}"
            [properties]
            gui_reference_clock_frequency = "50.0"
            gui_output_clock_frequency0 = "100.0"
            "#,
            output_dir.to_string_lossy().replace('\\', "/")
        ))
        .unwrap();

        let project_manifest: loom_core::manifest::ProjectManifest = toml::from_str(
            r#"
            [project]
            name = "test"
            top_module = "top"
            [target]
            part = "10CL025YU256C8G"
            backend = "quartus"
            "#,
        )
        .unwrap();
        let resolved = loom_core::resolve::resolver::ResolvedProject {
            project: project_manifest,
            project_root: tmp.path().to_path_buf(),
            workspace_root: tmp.path().to_path_buf(),
            resolved_components: vec![],
            platform: None,
            active_profile: None,
            variant_selections: std::collections::HashMap::new(),
            profile_params: std::collections::HashMap::new(),
        };
        let context =
            loom_core::build::context::BuildContext::new(resolved, tmp.path().to_path_buf());

        // Will fail with ToolNotFound (qsys-generate not installed),
        // but Tcl file should exist
        let _result = gen.execute(&config, &context);

        let tcl_path = output_dir.join("my_pll_gen.tcl");
        let tcl_content = std::fs::read_to_string(&tcl_path).unwrap();

        assert!(tcl_content.contains("package require -exact qsys"));
        assert!(tcl_content.contains("create_system my_pll"));
        assert!(tcl_content.contains("set_instance_parameter_value"));
        assert!(tcl_content.contains("save_system my_pll.ip"));
    }

    #[test]
    fn test_cache_key_includes_tool_version() {
        let gen = QuartusIpGenerator;
        let config1: toml::Value = toml::from_str(
            r#"
            ip_name = "my_pll"
            tool_version = "22.1"
            "#,
        )
        .unwrap();
        let config2: toml::Value = toml::from_str(
            r#"
            ip_name = "my_pll"
            tool_version = "23.1"
            "#,
        )
        .unwrap();
        let hashes = HashMap::new();
        let k1 = gen.compute_cache_key(&config1, &hashes).unwrap();
        let k2 = gen.compute_cache_key(&config2, &hashes).unwrap();
        assert_ne!(k1, k2);
    }

    #[test]
    fn test_cache_key_with_input_hashes() {
        let gen = QuartusIpGenerator;
        let config: toml::Value = toml::from_str("ip_name = \"my_pll\"").unwrap();
        let hashes_empty = HashMap::new();
        let mut hashes_with = HashMap::new();
        hashes_with.insert("config.tcl".to_string(), "sha256:abc123".to_string());

        let k1 = gen.compute_cache_key(&config, &hashes_empty).unwrap();
        let k2 = gen.compute_cache_key(&config, &hashes_with).unwrap();
        assert_ne!(k1, k2);
    }

    #[test]
    fn test_cache_key_changes_with_ip_name() {
        let gen = QuartusIpGenerator;
        let config1: toml::Value = toml::from_str("ip_name = \"pll_a\"").unwrap();
        let config2: toml::Value = toml::from_str("ip_name = \"pll_b\"").unwrap();
        let hashes = HashMap::new();
        let k1 = gen.compute_cache_key(&config1, &hashes).unwrap();
        let k2 = gen.compute_cache_key(&config2, &hashes).unwrap();
        assert_ne!(k1, k2);
    }
}
