use std::path::PathBuf;

use loom_core::assemble::fileset::{AssembledFilesets, FileLanguage};
use loom_core::build::context::BuildContext;
use loom_core::error::LoomError;
use loom_core::resolve::resolver::ResolvedProject;

/// Generate a Quartus Tcl build script.
pub fn generate_quartus_tcl(
    project: &ResolvedProject,
    filesets: &AssembledFilesets,
    _context: &BuildContext,
) -> Result<String, LoomError> {
    let project_name = &project.project.project.name;
    let target = project
        .project
        .target
        .as_ref()
        .ok_or_else(|| LoomError::Internal("Project has no target".to_string()))?;
    let part = &target.part;

    let mut tcl = String::new();

    // Header
    tcl.push_str("# Quartus build script\n");
    tcl.push_str("# Generated by loom — do not edit\n\n");

    // Project setup
    tcl.push_str("package require ::quartus::project\n");
    tcl.push_str(&format!("project_new {} -overwrite\n\n", project_name));

    // Device
    tcl.push_str(&format!("set_global_assignment -name DEVICE {}\n", part));
    tcl.push_str(&format!(
        "set_global_assignment -name TOP_LEVEL_ENTITY {}\n\n",
        project.project.project.top_module
    ));

    // Source files
    for file in &filesets.synth_files {
        let path_str = loom_core::util::to_tool_path(&file.path);
        match file.language {
            FileLanguage::SystemVerilog => {
                tcl.push_str(&format!(
                    "set_global_assignment -name SYSTEMVERILOG_FILE {}\n",
                    path_str
                ));
            }
            FileLanguage::Verilog => {
                tcl.push_str(&format!(
                    "set_global_assignment -name VERILOG_FILE {}\n",
                    path_str
                ));
            }
            FileLanguage::Vhdl => {
                tcl.push_str(&format!(
                    "set_global_assignment -name VHDL_FILE {}\n",
                    path_str
                ));
            }
            FileLanguage::Unknown => {
                tcl.push_str(&format!("# Skipping unknown file: {}\n", path_str));
            }
        }
    }

    // Constraint files (.sdc)
    for constraint in &filesets.constraint_files {
        let path_str = loom_core::util::to_tool_path(&constraint.path);
        let ext = constraint
            .path
            .extension()
            .and_then(|e| e.to_str())
            .unwrap_or("");
        match ext {
            "sdc" => {
                tcl.push_str(&format!(
                    "set_global_assignment -name SDC_FILE {}\n",
                    path_str
                ));
            }
            "qsf" => {
                tcl.push_str(&format!("source {}\n", path_str));
            }
            _ => {
                tcl.push_str(&format!("# Unknown constraint format: {}\n", path_str));
            }
        }
    }

    // Defines
    for define in &filesets.defines {
        tcl.push_str(&format!(
            "set_global_assignment -name VERILOG_MACRO \"{}\"\n",
            define
        ));
    }

    tcl.push('\n');

    // Compile
    tcl.push_str("load_package flow\n");
    tcl.push_str("execute_flow -compile\n\n");

    tcl.push_str("project_close\n");

    Ok(tcl)
}

/// Write the Quartus Tcl script to the build directory.
pub fn write_quartus_tcl(tcl: &str, context: &BuildContext) -> Result<PathBuf, LoomError> {
    std::fs::create_dir_all(&context.build_dir).map_err(|e| LoomError::Io {
        path: context.build_dir.clone(),
        source: e,
    })?;

    let path = context.build_dir.join("build.tcl");
    std::fs::write(&path, tcl).map_err(|e| LoomError::Io {
        path: path.clone(),
        source: e,
    })?;

    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use loom_core::assemble::fileset::{AssembledFile, FileLanguage};

    #[test]
    fn test_quartus_tcl_generation() {
        let project: loom_core::manifest::ProjectManifest = toml::from_str(
            r#"
[project]
name = "my_design"
top_module = "top"
[target]
part = "5CSEBA6U23I7"
backend = "quartus"
"#,
        )
        .unwrap();

        let resolved = loom_core::resolve::resolver::ResolvedProject {
            project,
            project_root: PathBuf::from("/project"),
            workspace_root: PathBuf::from("/workspace"),
            resolved_components: vec![],
            platform: None,
            active_profile: None,
            variant_selections: std::collections::HashMap::new(),
        };

        let filesets = AssembledFilesets {
            synth_files: vec![AssembledFile {
                path: PathBuf::from("/project/src/top.sv"),
                source_component: "my_design".to_string(),
                language: FileLanguage::SystemVerilog,
            }],
            sim_files: vec![],
            constraint_files: vec![],
            defines: vec!["DEBUG=1".to_string()],
        };

        let context = BuildContext::new(resolved.clone(), PathBuf::from("/workspace"));

        let tcl = generate_quartus_tcl(&resolved, &filesets, &context).unwrap();
        assert!(tcl.contains("project_new my_design"));
        assert!(tcl.contains("DEVICE 5CSEBA6U23I7"));
        assert!(tcl.contains("SYSTEMVERILOG_FILE"));
        assert!(tcl.contains("execute_flow -compile"));
        assert!(tcl.contains("VERILOG_MACRO \"DEBUG=1\""));
    }
}
