use std::collections::{HashMap, HashSet};
use std::path::Path;

use chrono::Utc;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::error::LoomError;
use crate::resolve::resolver::ResolvedProject;
use crate::resolve::workspace::MemberPath;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Lockfile {
    pub metadata: LockfileMetadata,
    #[serde(rename = "package", default)]
    pub packages: Vec<LockedPackage>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockfileMetadata {
    pub loom_version: String,
    pub generated_at: String,
    pub workspace_members: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    pub source: String,
    pub checksum: String,
    #[serde(default)]
    pub dependencies: Vec<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum LockfileStatus {
    Valid,
    Stale(Vec<String>),
    Missing,
}

/// Generate a lockfile from a resolved project.
pub fn generate_lockfile(
    resolved: &ResolvedProject,
    member_paths: &[MemberPath],
) -> Result<Lockfile, LoomError> {
    let workspace_members = member_paths
        .iter()
        .filter_map(|m| {
            m.path
                .strip_prefix(&resolved.workspace_root)
                .ok()
                .map(|rel| rel.to_string_lossy().replace('\\', "/"))
        })
        .collect();

    let packages = resolved
        .resolved_components
        .iter()
        .map(|comp| {
            let source = format!(
                "workspace:{}",
                comp.source_path
                    .strip_prefix(&resolved.workspace_root)
                    .map(|rel| rel.to_string_lossy().replace('\\', "/"))
                    .unwrap_or_default()
            );
            let checksum = compute_component_checksum(&comp.source_path)?;
            let dependencies = comp
                .manifest
                .dependencies
                .iter()
                .map(|(name, spec)| format!("{} {}", name, spec.version_string()))
                .collect();

            Ok(LockedPackage {
                name: comp.manifest.component.name.clone(),
                version: comp.resolved_version.to_string(),
                source,
                checksum,
                dependencies,
            })
        })
        .collect::<Result<Vec<_>, LoomError>>()?;

    Ok(Lockfile {
        metadata: LockfileMetadata {
            loom_version: env!("CARGO_PKG_VERSION").to_string(),
            generated_at: Utc::now().to_rfc3339(),
            workspace_members,
        },
        packages,
    })
}

/// Write lockfile to disk.
pub fn write_lockfile(lockfile: &Lockfile, workspace_root: &Path) -> Result<(), LoomError> {
    let path = workspace_root.join("loom.lock");
    let content =
        toml::to_string_pretty(lockfile).map_err(|e| LoomError::LockfileWrite {
            message: e.to_string(),
        })?;

    let content = format!(
        "# This file is auto-generated by Loom. Do not edit manually.\n\
         # Commit this file to version control.\n\n{}",
        content
    );

    std::fs::write(&path, content).map_err(|e| LoomError::Io { path, source: e })
}

/// Load lockfile from workspace root.
pub fn load_lockfile(workspace_root: &Path) -> Result<Option<Lockfile>, LoomError> {
    let path = workspace_root.join("loom.lock");
    if !path.exists() {
        return Ok(None);
    }

    let content =
        std::fs::read_to_string(&path).map_err(|e| LoomError::Io {
            path: path.clone(),
            source: e,
        })?;

    toml::from_str::<Lockfile>(&content)
        .map(Some)
        .map_err(|e| LoomError::LockfileParse {
            message: e.to_string(),
        })
}

/// Check if an existing lockfile is still valid.
pub fn check_staleness(
    lockfile: &Lockfile,
    resolved: &ResolvedProject,
    current_members: &[MemberPath],
) -> LockfileStatus {
    let mut reasons = Vec::new();

    let current_member_set: HashSet<String> = current_members
        .iter()
        .filter_map(|m| {
            m.path
                .strip_prefix(&resolved.workspace_root)
                .ok()
                .map(|rel| rel.to_string_lossy().replace('\\', "/"))
        })
        .collect();

    let locked_member_set: HashSet<String> =
        lockfile.metadata.workspace_members.iter().cloned().collect();

    if current_member_set != locked_member_set {
        let added: Vec<_> = current_member_set.difference(&locked_member_set).collect();
        let removed: Vec<_> = locked_member_set.difference(&current_member_set).collect();
        if !added.is_empty() {
            reasons.push(format!("New workspace members: {:?}", added));
        }
        if !removed.is_empty() {
            reasons.push(format!("Removed workspace members: {:?}", removed));
        }
    }

    let locked_packages: HashMap<&str, &LockedPackage> = lockfile
        .packages
        .iter()
        .map(|p| (p.name.as_str(), p))
        .collect();

    for comp in &resolved.resolved_components {
        let name = &comp.manifest.component.name;
        match locked_packages.get(name.as_str()) {
            None => reasons.push(format!("New dependency: {}", name)),
            Some(locked) => {
                if locked.version != comp.resolved_version.to_string() {
                    reasons.push(format!(
                        "Version changed for {}: {} -> {}",
                        name, locked.version, comp.resolved_version
                    ));
                }
            }
        }
    }

    for locked_name in locked_packages.keys() {
        if !resolved
            .resolved_components
            .iter()
            .any(|c| c.manifest.component.name == *locked_name)
        {
            reasons.push(format!("Removed dependency: {}", locked_name));
        }
    }

    if reasons.is_empty() {
        LockfileStatus::Valid
    } else {
        LockfileStatus::Stale(reasons)
    }
}

fn compute_component_checksum(component_dir: &Path) -> Result<String, LoomError> {
    let mut hasher = Sha256::new();

    let manifest_path = component_dir.join("component.toml");
    let content = std::fs::read(&manifest_path).map_err(|e| LoomError::Io {
        path: manifest_path,
        source: e,
    })?;
    hasher.update(&content);

    let result = hasher.finalize();
    Ok(format!("sha256:{}", hex::encode(result)))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::resolve::workspace::{
        discover_members, find_project, find_workspace_root, load_all_components,
    };
    use crate::resolve::resolver::{resolve_project, WorkspaceDependencySource};
    use std::path::PathBuf;

    fn fixture_path(name: &str) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../tests/fixtures")
            .join(name)
    }

    fn resolve_fixture(name: &str) -> (ResolvedProject, Vec<MemberPath>, PathBuf) {
        let fixture = fixture_path(name);
        let (root, ws_manifest) = find_workspace_root(&fixture).unwrap();
        let members = discover_members(&root, &ws_manifest).unwrap();
        let all_components = load_all_components(&members).unwrap();
        let (project_root, project_manifest) = find_project(&members, None).unwrap();
        let source = WorkspaceDependencySource::new(all_components);
        let resolved = resolve_project(project_manifest, project_root, root.clone(), &source).unwrap();
        (resolved, members, root)
    }

    #[test]
    fn test_generate_and_roundtrip_lockfile() {
        let (resolved, members, root) = resolve_fixture("simple_project");
        let lockfile = generate_lockfile(&resolved, &members).unwrap();

        assert_eq!(lockfile.packages.len(), 1);
        assert_eq!(lockfile.packages[0].name, "testorg/axi_common");
        assert!(lockfile.packages[0].checksum.starts_with("sha256:"));

        // Write and reload
        let temp_dir = std::env::temp_dir().join("loom_lockfile_test");
        std::fs::create_dir_all(&temp_dir).unwrap();
        write_lockfile(&lockfile, &temp_dir).unwrap();

        let reloaded = load_lockfile(&temp_dir).unwrap().unwrap();
        assert_eq!(reloaded.packages.len(), 1);
        assert_eq!(reloaded.packages[0].name, lockfile.packages[0].name);

        // Clean up
        let _ = std::fs::remove_dir_all(&temp_dir);
    }

    #[test]
    fn test_staleness_valid() {
        let (resolved, members, _) = resolve_fixture("simple_project");
        let lockfile = generate_lockfile(&resolved, &members).unwrap();
        let status = check_staleness(&lockfile, &resolved, &members);
        assert_eq!(status, LockfileStatus::Valid);
    }

    #[test]
    fn test_staleness_new_dependency() {
        let (resolved, members, _) = resolve_fixture("simple_project");
        let mut lockfile = generate_lockfile(&resolved, &members).unwrap();
        // Remove a package from the lockfile to simulate a new dep
        lockfile.packages.clear();
        let status = check_staleness(&lockfile, &resolved, &members);
        match status {
            LockfileStatus::Stale(reasons) => {
                assert!(reasons.iter().any(|r| r.contains("New dependency")));
            }
            _ => panic!("Expected Stale"),
        }
    }
}
