#!/usr/bin/env python3
"""Generate window function LUT as a .mem file for $readmemh.

Usage:
    python3 gen_window_lut.py --type hann --size 256 --width 16 --output window_lut.mem

Requires: numpy (optional — falls back to math-based implementation)
"""

import argparse
import math
import os
import sys


def generate_window(win_type, size):
    """Generate window coefficients (0.0 to 1.0 range)."""
    if win_type == "hann":
        return [0.5 * (1.0 - math.cos(2.0 * math.pi * i / (size - 1))) for i in range(size)]
    elif win_type == "hamming":
        return [0.54 - 0.46 * math.cos(2.0 * math.pi * i / (size - 1)) for i in range(size)]
    elif win_type == "rectangular":
        return [1.0] * size
    else:
        print(f"Unknown window type: {win_type}", file=sys.stderr)
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(description="Generate window function LUT .mem file")
    parser.add_argument("--type", default="hann", choices=["hann", "hamming", "rectangular"],
                        help="Window function type")
    parser.add_argument("--size", type=int, default=256, help="LUT size (number of entries)")
    parser.add_argument("--width", type=int, default=16, help="Output bit width (unsigned)")
    parser.add_argument("--output", required=True, help="Output .mem file path")
    args = parser.parse_args()

    coeffs = generate_window(args.type, args.size)

    # Quantize to unsigned fixed-point
    scale = (1 << args.width) - 1
    qvals = [min(scale, max(0, int(round(c * scale)))) for c in coeffs]

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)

    hex_width = (args.width + 3) // 4
    with open(args.output, "w") as f:
        f.write(f"// Window LUT: type={args.type}, size={args.size}, width={args.width}\n")
        f.write(f"// Generated by gen_window_lut.py — DO NOT EDIT\n")
        for q in qvals:
            f.write(f"{q:0{hex_width}X}\n")

    print(f"  wrote {args.output} ({args.size} entries, {args.width}-bit unsigned)")


if __name__ == "__main__":
    main()
