"""
vivado_bd generator plugin — regenerates Vivado block design from canonical Tcl.

Usage in component.toml:
    [[generators]]
    name = "system_bd"
    plugin = "vivado_bd"
    inputs = ["bd/system.tcl"]
    outputs = ["bd/system/system.bd"]
    [generators.config]
    bd_tcl = "bd/system.tcl"
"""
import json
import os
import subprocess
import sys
import hashlib

from .plugin import GeneratorPlugin


class VivadoBdGenerator(GeneratorPlugin):
    """Regenerate a Vivado block design (.bd) from a canonical Tcl export."""

    def name(self) -> str:
        return "vivado_bd"

    def generate(self, config: dict, context: dict) -> dict:
        bd_tcl = config.get("bd_tcl", "")
        if not bd_tcl:
            return {"success": False, "error": "No bd_tcl specified in config"}

        # Resolve path relative to component root
        component_root = context.get("component_root", ".")
        bd_tcl_path = os.path.join(component_root, bd_tcl)

        if not os.path.exists(bd_tcl_path):
            return {"success": False, "error": f"bd_tcl not found: {bd_tcl_path}"}

        output_dir = context.get("output_dir", ".")
        os.makedirs(output_dir, exist_ok=True)

        # Generate Vivado batch script to regenerate BD
        regen_tcl = os.path.join(output_dir, "regen_bd.tcl")
        part = context.get("part", "")
        project_name = context.get("project_name", "temp_bd_project")

        with open(regen_tcl, "w") as f:
            f.write(f"# Auto-generated by loom vivado_bd plugin\n")
            f.write(f"create_project -in_memory {project_name}\n")
            if part:
                f.write(f"set_property part {part} [current_project]\n")
            f.write(f"source {{{bd_tcl_path}}}\n")
            f.write(f"regenerate_bd_layout\n")
            f.write(f"validate_bd_design\n")
            f.write(f"save_bd_design\n")

        return {
            "success": True,
            "outputs": [regen_tcl],
            "message": f"Generated BD regeneration script from {bd_tcl}",
        }

    def compute_hash(self, config: dict, context: dict) -> str:
        bd_tcl = config.get("bd_tcl", "")
        component_root = context.get("component_root", ".")
        bd_tcl_path = os.path.join(component_root, bd_tcl)

        h = hashlib.sha256()
        if os.path.exists(bd_tcl_path):
            with open(bd_tcl_path, "rb") as f:
                h.update(f.read())
        h.update(context.get("part", "").encode())
        h.update(context.get("tool_version", "").encode())
        return h.hexdigest()


def main():
    gen = VivadoBdGenerator()
    gen.main()


if __name__ == "__main__":
    main()
