use std::path::PathBuf;

use loom_core::assemble::fileset::{AssembledFilesets, FileLanguage};
use loom_core::build::context::BuildContext;
use loom_core::error::LoomError;
use loom_core::resolve::resolver::ResolvedProject;

/// Generate Radiant Tcl build script.
pub fn generate_radiant_tcl(
    project: &ResolvedProject,
    filesets: &AssembledFilesets,
    _context: &BuildContext,
) -> Result<String, LoomError> {
    let target = project
        .project
        .target
        .as_ref()
        .ok_or_else(|| LoomError::Internal("Project has no target".to_string()))?;

    let mut tcl = String::new();

    // Header
    tcl.push_str("# Auto-generated by Loom - do not edit\n");
    tcl.push_str(&format!("# Project: {}\n\n", project.project.project.name));

    // Create project
    tcl.push_str(&format!(
        "prj_create -name \"{}\" -impl \"impl\" -dev {} -synthesis \"synplify\"\n\n",
        project.project.project.top_module, target.part
    ));

    // Add source files
    tcl.push_str("# Source files\n");
    for file in &filesets.synth_files {
        let path = file.path.display().to_string().replace('\\', "/");
        match file.language {
            FileLanguage::Vhdl => {
                tcl.push_str(&format!("prj_src add -format VHDL \"{}\"\n", path));
            }
            FileLanguage::SystemVerilog | FileLanguage::Verilog => {
                tcl.push_str(&format!("prj_src add -format Verilog \"{}\"\n", path));
            }
            _ => {
                tcl.push_str(&format!("prj_src add \"{}\"\n", path));
            }
        }
    }

    // Add constraint files
    tcl.push_str("\n# Constraints\n");
    for constraint in &filesets.constraint_files {
        let path = constraint.path.display().to_string().replace('\\', "/");
        tcl.push_str(&format!("prj_src add -format PDC \"{}\"\n", path));
    }

    // Set top module
    tcl.push_str(&format!(
        "\n# Set top module\nprj_src top -module \"{}\"\n\n",
        project.project.project.top_module
    ));

    // Run flow
    tcl.push_str("# Run synthesis\nprj_run Synthesis -impl impl\n");
    tcl.push_str("# Run map\nprj_run Map -impl impl\n");
    tcl.push_str("# Run place & route\nprj_run PAR -impl impl\n");

    // Generate bitstream
    tcl.push_str("# Generate bitstream\nprj_run Export -impl impl -task Bitstream\n");

    tcl.push_str("\nprj_close\n");

    Ok(tcl)
}

/// Write the Radiant Tcl script to disk.
pub fn write_radiant_tcl(script: &str, context: &BuildContext) -> Result<PathBuf, LoomError> {
    let script_path = context.build_dir.join("build_radiant.tcl");
    std::fs::create_dir_all(&context.build_dir).map_err(|e| LoomError::Io {
        path: context.build_dir.clone(),
        source: e,
    })?;
    std::fs::write(&script_path, script).map_err(|e| LoomError::Io {
        path: script_path.clone(),
        source: e,
    })?;
    Ok(script_path)
}

#[cfg(test)]
mod tests {
    #[test]
    fn test_script_contains_project_create() {
        // Basic smoke test: just verify the template structure
        let tcl = "prj_create -name \"top\" -impl \"impl\" -dev LIFCL-40";
        assert!(tcl.contains("prj_create"));
        assert!(tcl.contains("LIFCL-40"));
    }
}
